/**
 * lib/keywords.ts
 * Categorized keyword/phrase dictionary for sensitive topic detection.
 * Covers political figures, ideologies, policy issues, and legal/regulatory terms.
 */

// ─── Political Figures ───────────────────────────────────────────────────────

export const politicalFigures: string[] = [
  // ── Notable non-English historical/public figures ──
  "Hitler",
  "Adolf Hitler",
  "Stalin",
  "Joseph Stalin",
  "Mao",
  "Mao Zedong",
  "Mao Tse-tung",
  "Putin",
  "Vladimir Putin",
  "Zelensky",
  "Volodymyr Zelensky",
  "Xi Jinping",
  "Xi",

  // ── Political Parties (Canada) ──
  "Liberal Party",
  "Conservative Party",
  "NDP",
  "New Democratic Party",
  "Green Party",
  "Bloc Québécois",
  "Bloc Quebecois",
  "People's Party",
  "People's Party of Canada",
  "Reform Party",
  "Canadian Alliance",
  "Progressive Conservative",
  "Alberta Party",
  "Wildrose",
  "United Conservative Party",
  "UCP",
  "Alberta NDP",

  // ── Political Parties (United States) ──
  "Republican Party",
  "Democratic Party",
  "GOP",
  "Libertarian Party",

  // ── Political Parties (United Kingdom) ──
  "Conservative Party UK",
  "Labour Party",
  "Liberal Democrats",
  "Scottish National Party",
  "SNP",
  "Sinn Féin",
  "Sinn Fein",
  "DUP",
  "Democratic Unionist Party",
  "Plaid Cymru",
  "UKIP",
  "Reform UK",

  // ── Political Parties (Australia) ──
  "Australian Labor Party",
  "ALP",
  "Liberal Party of Australia",
  "Australian Greens",
  "National Party of Australia",
  "One Nation",

  // ── Political Parties (New Zealand) ──
  "New Zealand Labour",
  "New Zealand National Party",
  "ACT New Zealand",
  "Green Party of Aotearoa",
  "NZ First",

  // ── Canada – Federal Politicians (historical and recent) ──
  "John A. Macdonald",
  "John A Macdonald",
  "Wilfrid Laurier",
  "Robert Borden",
  "Mackenzie King",
  "William Lyon Mackenzie King",
  "Louis St. Laurent",
  "Louis St Laurent",
  "John Diefenbaker",
  "Lester Pearson",
  "Pierre Trudeau",
  "Pierre Elliott Trudeau",
  "Joe Clark",
  "John Turner",
  "Brian Mulroney",
  "Kim Campbell",
  "Jean Chrétien",
  "Jean Chretien",
  "Paul Martin",
  "Stephen Harper",
  "Justin Trudeau",
  "Mark Carney",
  "Jagmeet Singh",
  "Pierre Poilievre",
  "Yves-François Blanchet",
  "Elizabeth May",
  "Maxime Bernier",
  "Chrystia Freeland",
  "Erin O'Toole",
  "Andrew Scheer",
  "Tom Mulcair",
  "Jack Layton",
  "Stéphane Dion",
  "Stephane Dion",
  "Michael Ignatieff",
  "Stockwell Day",
  "Preston Manning",
  "Belinda Stronach",
  "Peter MacKay",
  "Jason Kenney",
  "Rona Ambrose",
  "Candice Bergen",
  "Carolyn Bennett",
  "Bill Blair",
  "Randy Boissonnault",
  "François-Philippe Champagne",
  "Francois-Philippe Champagne",
  "Sean Fraser",
  "Mélanie Joly",
  "Melanie Joly",
  "David Lametti",
  "Marco Mendicino",
  "Ahmed Hussen",
  "Pablo Rodriguez",
  "Jonathan Wilkinson",
  "Steven Guilbeault",
  "Marc Miller",
  "Gary Anandasangaree",
  "Carla Qualtrough",
  "Karina Gould",
  "Patty Hajdu",
  "Jean-Yves Duclos",
  "Seamus O'Regan",
  "Michael Chong",
  "Marilyn Gladu",
  "Michelle Rempel Garner",
  "Michelle Rempel",
  "Tony Clement",
  "Rob Nicholson",

  // ── Canada – Senate ──
  "Mike Duffy",
  "Pamela Wallin",
  "Patrick Brazeau",

  // ── Alberta Provincial Politicians ──
  "Peter Lougheed",
  "Don Getty",
  "Ralph Klein",
  "Ed Stelmach",
  "Alison Redford",
  "Dave Hancock",
  "Jim Prentice",
  "Rachel Notley",
  "Jason Kenney",
  "Danielle Smith",
  "Travis Toews",
  "Brian Jean",
  "Ric McIver",
  "Miranda Rosin",
  "Tyler Shandro",
  "Adriana LaGrange",
  "Kaycee Madu",
  "Mike Ellis",
  "Nate Horner",
  "Deron Bilous",
  "Shannon Phillips",
  "Sarah Hoffman",
  "David Shepherd",
  "Rakhi Pancholi",
  "Kathleen Ganley",
  "Chris Nielsen",
  "Thomas Dang",
  "Jon Carson",
  "Marie Renaud",
  "Janis Irwin",
  "Lori Sigurdson",
  "Joe Ceci",
  "Irfan Sabir",

  // ── Calgary City Council & Mayor ──
  "Jyoti Gondek",
  "Naheed Nenshi",
  "Dave Bronconnier",
  "Al Duerr",
  "Andy Penman",
  "Jan Reimer",
  "Rod Sykes",
  "Peter Lougheed",    // also provincial
  "Andre Chabot",
  "Sonya Sharp",
  "Sean Chu",
  "Shane Keating",
  "Gian-Carlo Carra",
  "Evan Spencer",
  "Terry Wong",
  "Peter Demong",
  "Jennifer Wyness",
  "Courtney Walcott",
  "Kourtney Penner",
  "Richard Pootmans",
  "Dan McLean",
  "Jasmine Mian",
  "Raj Dhaliwal",
  "Rezaul Chowdhury",

  // ── Edmonton City Council & Mayor ──
  "Amarjeet Sohi",
  "Don Iveson",
  "Stephen Mandel",
  "Bill Smith",
  "Dave Bronconnier",  // served both
  "Jan Reimer",        // also Calgary reference
  "Lawrence Decore",
  "Keren Tang",
  "Anne Stevenson",
  "Michael Janz",
  "Jo-Anne Wright",
  "Aaron Paquette",
  "Erin Rutherford",
  "Karen Principe",
  "Tim Cartmell",
  "Andrew Knack",
  "Ashley Salvador",
  "Janis Irwin",       // MLA but local figure
  "Sarah Hamilton",
  "Stephanie Smyth",

  // ── United States – Presidents & Key Figures ──
  "Franklin Roosevelt",
  "FDR",
  "Harry Truman",
  "Dwight Eisenhower",
  "John F. Kennedy",
  "John F Kennedy",
  "JFK",
  "Lyndon Johnson",
  "LBJ",
  "Richard Nixon",
  "Gerald Ford",
  "Jimmy Carter",
  "Ronald Reagan",
  "George H.W. Bush",
  "George HW Bush",
  "Bill Clinton",
  "George W. Bush",
  "George W Bush",
  "Barack Obama",
  "Donald Trump",
  "Joe Biden",
  "Kamala Harris",
  "Hillary Clinton",
  "Bernie Sanders",
  "Alexandria Ocasio-Cortez",
  "AOC",
  "Nancy Pelosi",
  "Mitch McConnell",
  "Mike Pence",
  "Ron DeSantis",
  "Nikki Haley",
  "Vivek Ramaswamy",
  "JD Vance",
  "Elon Musk",
  "Robert F. Kennedy Jr",
  "RFK Jr",
  "Marco Rubio",
  "Ted Cruz",
  "Rand Paul",
  "Elizabeth Warren",
  "Pete Buttigieg",
  "Gavin Newsom",

  // ── United Kingdom – Prime Ministers & Key Figures ──
  "Winston Churchill",
  "Clement Attlee",
  "Anthony Eden",
  "Harold Macmillan",
  "Alec Douglas-Home",
  "Harold Wilson",
  "Edward Heath",
  "James Callaghan",
  "Margaret Thatcher",
  "John Major",
  "Tony Blair",
  "Gordon Brown",
  "David Cameron",
  "Theresa May",
  "Boris Johnson",
  "Liz Truss",
  "Rishi Sunak",
  "Keir Starmer",
  "Nigel Farage",
  "Jeremy Corbyn",
  "Ed Miliband",

  // ── Australia – Prime Ministers & Key Figures ──
  "Robert Menzies",
  "Gough Whitlam",
  "Malcolm Fraser",
  "Bob Hawke",
  "Paul Keating",
  "John Howard",
  "Kevin Rudd",
  "Julia Gillard",
  "Tony Abbott",
  "Malcolm Turnbull",
  "Scott Morrison",
  "Anthony Albanese",
  "Peter Dutton",
  "Adam Bandt",

  // ── New Zealand – Prime Ministers & Key Figures ──
  "Jacinda Ardern",
  "Chris Hipkins",
  "Christopher Luxon",
  "Winston Peters",
  "David Seymour",
  "Bill English",
  "John Key",
  "Helen Clark",
];

// ─── Ideologies ──────────────────────────────────────────────────────────────

export const ideologies: string[] = [
  "Fascism",
  "Fascist",
  "Neo-Fascism",
  "Neo-Fascist",
  "Communism",
  "Communist",
  "Marxism",
  "Marxist",
  "Leninism",
  "Leninist",
  "Maoism",
  "Maoist",
  "Stalinism",
  "Stalinist",
  "Socialism",
  "Socialist",
  "Democratic Socialism",
  "Democratic Socialist",
  "Nationalism",
  "Nationalist",
  "Ethno-Nationalism",
  "Ethno-Nationalist",
  "White Nationalism",
  "White Nationalist",
  "White Supremacy",
  "White Supremacist",
  "Conservatism",
  "Conservative",
  "Social Conservatism",
  "Social Conservative",
  "Fiscal Conservatism",
  "Fiscal Conservative",
  "Neo-Conservatism",
  "Neo-Conservative",
  "Neocon",
  "Liberalism",
  "Liberal",
  "Classical Liberalism",
  "Classical Liberal",
  "Neo-Liberalism",
  "Neo-Liberal",
  "Progressive",
  "Progressivism",
  "Feminism",
  "Feminist",
  "Radical Feminism",
  "Radical Feminist",
  "Environmentalism",
  "Environmentalist",
  "Eco-Socialism",
  "Eco-Socialist",
  "Libertarianism",
  "Libertarian",
  "Anarchism",
  "Anarchist",
  "Populism",
  "Populist",
  "Authoritarianism",
  "Authoritarian",
  "Totalitarianism",
  "Totalitarian",
  "Separatism",
  "Separatist",
  "Anti-Semitism",
  "Anti-Semitic",
  "Islamophobia",
  "Islamophobic",
  "Racism",
  "Racist",
  "Woke",
  "Wokeism",
  "Alt-right",
  "Far-right",
  "Far-left",
  "Extremism",
  "Extremist",
  "Radicalism",
  "Radical",
];

// ─── Political / Policy Issues ───────────────────────────────────────────────

export const politicalIssues: string[] = [
  // ── International Conflicts & Geopolitics ──
  "Israel",
  "Palestine",
  "Israeli-Palestinian",
  "Gaza",
  "West Bank",
  "Hamas",
  "Hezbollah",
  "Iran War",
  "Iran nuclear",
  "NATO",
  "CUSMA",
  "USMCA",
  "NAFTA",
  "Tariffs",
  "Trade war",
  "Ukraine",
  "Russia-Ukraine",
  "Sovereignty",
  "United Nations",
  "UN Security Council",
  "Davos",
  "World Economic Forum",
  "WEF",
  "COP26",
  "COP27",
  "COP28",
  "COP29",
  "COP conference",
  "Paris Agreement",
  "Kyoto Protocol",

  // ── Indigenous Issues ──
  "Residential schools",
  "Indian residential school",
  "Residential school survivors",
  "Truth and reconciliation",
  "Truth and Reconciliation Commission",
  "TRC",
  "Missing and murdered indigenous women",
  "MMIWG",
  "Missing and murdered indigenous women and girls",
  "Indigenous rights",
  "First Nations",
  "Métis",
  "Metis",
  "Inuit",
  "UNDRIP",
  "Land acknowledgement",
  "Indian Act",

  // ── LGBTQ+ & Gender ──
  "2SLGBTQI+",
  "LGBTQ",
  "LGBTQ+",
  "LGBTQI",
  "LGBT",
  "Same-sex marriage",
  "Trans rights",
  "Transgender",
  "Gender identity",
  "Gender expression",
  "Non-binary",
  "Conversion therapy",
  "Drag",
  "Pronoun",

  // ── DEI & Social Justice ──
  "DEI",
  "Diversity equity inclusion",
  "Diversity, equity and inclusion",
  "Diversity and inclusion",
  "Equity",
  "Affirmative action",
  "Anti-racism",
  "Systemic racism",
  "Critical race theory",
  "CRT",
  "Defund the police",
  "Black Lives Matter",
  "BLM",
  "Cancel culture",
  "Woke agenda",

  // ── Energy & Environment ──
  "Carbon tax",
  "Carbon price",
  "Carbon pricing",
  "Emissions regulation",
  "Emissions trading",
  "Cap and trade",
  "Greenhouse gas",
  "GHG emissions",
  "Pipelines",
  "Trans Mountain",
  "Keystone XL",
  "Line 5",
  "Northern Gateway",
  "Energy East",
  "Oil sands",
  "Tar sands",
  "Oilfield",
  "Petroleum industry",
  "Equalization",
  "Equalization payments",
  "Methane emissions",
  "Methane regulation",
  "Fertilizer regulation",
  "Nitrogen oxide emissions",
  "NOx emissions",
  "Alberta Energy Regulator",
  "AER",
  "Canadian Energy Regulator",
  "CER",
  "Coal mining",
  "Coal-fired",
  "Thermal coal",
  "Oil",
  "Natural gas",
  "Wind energy",
  "Solar energy",
  "Nuclear energy",
  "Nuclear power",
  "Renewable energy",
  "Forest fire management",
  "Wildfire management",
  "Logging industry",
  "Clear cutting",
  "Deforestation",
  "Electricity rates",
  "Water rates",
  "Cell phone rates",
  "Telecom rates",

  // ── Healthcare ──
  "COVID-19",
  "COVID",
  "Coronavirus",
  "Pandemic",
  "Vaccine mandate",
  "Vaccine passport",
  "AHS restructuring",
  "Alberta Health Services",
  "Public healthcare",
  "Private healthcare",
  "Two-tier healthcare",
  "Healthcare privatization",
  "Ambulance response times",
  "Alberta Medical Association",
  "AMA",
  "Emergency room wait times",
  "ER wait times",
  "Family doctor availability",
  "Doctor shortage",
  "Physician shortage",
  "Hospital bed space",
  "Hospital capacity",
  "MAID",
  "Medical assistance in dying",
  "Euthanasia",
  "Mental health",
  "Addiction",
  "Supervised consumption",
  "Supervised consumption site",
  "SCS",
  "Safe supply",
  "Drug decriminalization",
  "Opioid crisis",
  "Fentanyl",
  "Recovery community",
  "Abstinence-based recovery",

  // ── Education ──
  "Teachers strike",
  "Teacher strike",
  "Classroom sizes",
  "Class sizes",
  "Classroom complexity",
  "Teacher pay",
  "Teacher salary",
  "Alberta Teachers Association",
  "ATA",
  "K-12 curriculum",
  "K-12 education",
  "Curriculum reform",
  "School curriculum",
  "University tuition",
  "Tuition fees",
  "Post-secondary funding",
  "International students",
  "Student visa",
  "Arts funding",
  "Arts council",

  // ── Immigration ──
  "Immigration",
  "Immigrant",
  "Refugee",
  "Asylum seeker",
  "Border security",
  "Deportation",
  "Temporary Foreign Worker",
  "Temporary Foreign Worker Program",
  "TFWP",
  "Foreign worker",
  "Open work permit",

  // ── Housing & Affordability ──
  "Housing costs",
  "Housing affordability",
  "Affordable housing",
  "Homelessness",
  "Rent control",
  "Vacancy tax",
  "Speculation tax",
  "Affordability crisis",
  "Cost of living",
  "Inflation",
  "Interest rates",
  "Bank of Canada",

  // ── Criminal Justice ──
  "Mandatory minimum sentences",
  "Mandatory minimum",
  "Sentencing reform",
  "Bail reform",
  "Criminal justice reform",
  "Policing",
  "Police defunding",
  "Police brutality",
  "RCMP",
  "Guns",
  "Gun control",
  "Firearms",
  "Handgun ban",
  "Assault-style firearms",
  "AR-15",
  "Long-gun registry",

  // ── Fiscal & Taxation ──
  "Property tax",
  "Income tax",
  "Corporate tax",
  "Wealth tax",
  "Capital gains tax",
  "Pension",
  "CPP",
  "Canada Pension Plan",
  "OAS",
  "Old Age Security",
  "AISH",
  "Assured Income for the Severely Handicapped",
  "Income support",
  "Welfare",
  "Social assistance",

  // ── Transit & Infrastructure ──
  "Transit",
  "Public transit",
  "LRT",
  "Light rail",
  "Green Line",
  "Bus rapid transit",
  "BRT",
  "Highway expansion",
  "Infrastructure spending",
];

// ─── Legal / Regulatory ──────────────────────────────────────────────────────

export const legalRegulatory: string[] = [
  // ── Judicial Decisions ──
  "Supreme Court of Canada",
  "SCC ruling",
  "Federal Court",
  "Court of Appeal",
  "Charter of Rights",
  "Charter challenge",
  "Section 33",
  "Notwithstanding clause",
  "Judicial review",
  "Injunction",
  "Class action",
  "Expropriation",
  "Rule of law",

  // ── Federal Legislation ──
  "Bill C-11",
  "Bill C-18",
  "Bill C-21",
  "Bill C-69",
  "Bill C-48",
  "Bill C-92",
  "Impact Assessment Act",
  "Online Streaming Act",
  "Online News Act",
  "Firearms Act",
  "Criminal Code",
  "Emergencies Act",
  "Constitution Act",
  "Clarity Act",
  "Indian Act",
  "Privacy Act",
  "PIPEDA",
  "Access to Information",
  "Freedom of Information",
  "FOIP",
  "Official Languages Act",
  "Immigration and Refugee Protection Act",
  "IRPA",
  "Canada Health Act",
  "Pension Benefits Standards Act",
  "Competition Act",
  "Broadcasting Act",
  "Telecommunications Act",
  "Cannabis Act",
  "Safe Third Country Agreement",
  "Extradition",

  // ── Provincial Legislation (Alberta) ──
  "Alberta Sovereignty Act",
  "Sovereignty Act",
  "Electricity Statutes Amendment Act",
  "Public Health Act",
  "Education Act",
  "School Act",
  "Labour Relations Code",
  "Fiscal Responsibility Act",
  "Municipal Government Act",
  "Land Titles Act",
  "Mines and Minerals Act",
  "Environmental Protection and Enhancement Act",
  "EPEA",
  "Water Act",
  "Occupational Health and Safety Act",
  "OHS Act",
  "Alberta Human Rights Act",
  "Landlord and Tenant legislation",
  "Residential Tenancies Act",

  // ── Public Agencies – Federal ──
  "CRTC",
  "Canadian Radio-television and Telecommunications Commission",
  "CBC",
  "Canadian Broadcasting Corporation",
  "Elections Canada",
  "RCMP",
  "CSIS",
  "CSE",
  "Communications Security Establishment",
  "CRA",
  "Canada Revenue Agency",
  "Immigration, Refugees and Citizenship Canada",
  "IRCC",
  "Health Canada",
  "Environment and Climate Change Canada",
  "Transport Canada",
  "Canadian Grain Commission",
  "National Energy Board",
  "NEB",
  "Office of the Privacy Commissioner",
  "Correctional Service Canada",
  "Parole Board of Canada",
  "Canada Border Services Agency",
  "CBSA",
  "National Defence",
  "DND",
  "Canadian Armed Forces",
  "CAF",
  "Office of the Auditor General",
  "OAG",
  "Bank of Canada",
  "Competition Bureau",
  "Financial Consumer Agency of Canada",
  "FCAC",
  "Invest in Canada",
  "Export Development Canada",
  "EDC",
  "Business Development Bank",
  "BDC",
  "Farm Credit Canada",
  "FCC",
  "Atomic Energy of Canada",
  "AECL",
  "Canadian Nuclear Safety Commission",
  "CNSC",
  "National Film Board",
  "NFB",
  "Canada Council for the Arts",
  "Social Sciences and Humanities Research Council",
  "SSHRC",
  "Natural Sciences and Engineering Research Council",
  "NSERC",
  "Canadian Institutes of Health Research",
  "CIHR",
  "Statistics Canada",
  "Library and Archives Canada",

  // ── Public Agencies – Alberta ──
  "Alberta Energy Regulator",
  "AER",
  "Alberta Utilities Commission",
  "AUC",
  "Alberta Securities Commission",
  "ASC",
  "Alberta Health Services",
  "AHS",
  "Alberta Gaming, Liquor and Cannabis Commission",
  "AGLC",
  "Service Alberta",
  "ATB Financial",
  "Alberta Treasury Branches",
  "Agriculture Financial Services Corporation",
  "AFSC",
  "Alberta Innovates",
  "Alberta Health",
  "Alberta Education",
  "Alberta Justice",
  "Alberta Environment",
  "Alberta Municipal Affairs",
  "Alberta Transportation",
  "Alberta Indigenous Relations",
  "Alberta Public Service Commission",
  "Alberta Workers' Compensation Board",
  "WCB",
  "AISH",
  "Assured Income for the Severely Handicapped",
  "Human Services",
  "Alberta Child and Family Services",
  "Child Intervention",
  "Subdivision and Development Appeal Board",
  "SDAB",
  "Land Compensation Board",
  "Surface Rights Board",
  "Labour Relations Board",
  "LRB",
  "Law Enforcement Review Board",
  "LERB",
  "Alberta Ombudsman",
  "Information and Privacy Commissioner",
  "IPC",
  "Ethics Commissioner",
  "Election Commissioner",
  "Child and Youth Advocate",
  "Office of the Public Interest Commissioner",
  "OPIC",
  "Alberta Court of King's Bench",
  "Court of King's Bench",
  "Alberta Court of Appeal",
  "Provincial Court of Alberta",
  "Alberta Human Rights Commission",

  // ── Professional Discipline ──
  "College of Physicians and Surgeons",
  "CPSA",
  "Alberta College of Pharmacy",
  "Alberta Dental Association",
  "Law Society of Alberta",
  "LSA",
  "Association of Professional Engineers",
  "APEGA",
  "Alberta Veterinary Medical Association",
  "ABVMA",
  "Alberta College of Social Workers",
  "ACSW",
  "College of Registered Nurses",
  "CARNA",
  "College of Licensed Practical Nurses",
  "CLPNA",
  "College of Paramedics",
  "Physiotherapy Alberta",
  "College of Optometrists",
  "Real Estate Council of Alberta",
  "RECA",
  "Insurance Council of Alberta",
  "Chartered Professional Accountants",
  "CPA Alberta",
  "Alberta Architects Act",
  "AIBC",
  "Professional discipline",
  "Disciplinary proceedings",
  "License revocation",
  "Suspension of licence",
  "Regulatory tribunal",
  "Regulatory body",
];

// ─── Category Map ─────────────────────────────────────────────────────────────

const CATEGORIES: Record<string, string[]> = {
  politicalFigures,
  ideologies,
  politicalIssues,
  legalRegulatory,
};

// ─── flagContent ──────────────────────────────────────────────────────────────

/**
 * Scans `text` for keywords from every category.
 * Returns an array of `{ category, matches }` for each category that has at
 * least one match. Matching is case-insensitive. Duplicate matches within a
 * category are deduplicated.
 *
 * @param text - The content to scan.
 * @returns Array of category results, omitting categories with no matches.
 */
export function flagContent(text: string): { category: string; matches: string[] }[] {
  const lower = text.toLowerCase();
  const results: { category: string; matches: string[] }[] = [];

  for (const [category, keywords] of Object.entries(CATEGORIES)) {
    const matched = new Set<string>();

    for (const keyword of keywords) {
      if (lower.includes(keyword.toLowerCase())) {
        matched.add(keyword);
      }
    }

    if (matched.size > 0) {
      results.push({ category, matches: Array.from(matched) });
    }
  }

  return results;
}
